version: "3"
services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - "27018:27017"
    healthcheck:
      test: ["CMD-SHELL", "mongo --eval 'db.runCommand({ ping: 1 })' || exit 1"]
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - backend-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - backend-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/clinica
    

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - backend-network
networks:
  backend-network:
    driver: bridge
volumes:
  mongo-data:
    driver: local
